enable-custom-guide: true
debug: false

web-editor:
  enabled: false
  port: 8899
  bind: "127.0.0.1"
  token: ""
  editors:
    categories: false
    recipes: false
    researches: false
  auto-load-recipes: true
  auto-load-categories: true
