name: SlimefunWeaver
version: '${project.version}'
main: cn.rmc.slimefunweaver.SlimefunWeaver
api-version: 1.16
depend:
  - Slimefun
commands:
  slimefunweaver:
    description: SlimefunWeaver commands
    usage: /scg <export|reload>
    aliases: [scg]
permissions:
  slimefunweaver.export:
    description: Allow exporting categories
    default: op
  slimefunweaver.reload:
    description: Allow reloading categories
    default: op
